GET http://localhost:8000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicGllcnJvIiwiaWF0IjoxNjgxNjYyNzM5fQ.d6_9hQaR6hAk2tUjvmjBu5ObFSruex_dHVGcxvPq_WQ

################################
POST http://localhost:8000/users
Content-Type: application/json

{
    "name": "pierro",
    "password": "123456",
    "title": "Je suis en vacances"
}
################################
POST http://localhost:8000/users/login
Content-Type: application/json

{
    "name": "pierro",
    "password": "123456"
}

################################
GET http://localhost:3002/posts

################################
POST http://localhost:3002/users/login
Content-Type: application/json

{
    "name": "Laura",
    "password": "qwerty"
}